# Generated by Django 5.2.16 on 2026-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Text added to the display name, e.g. [FC] or ~AFK~', max_length=32, unique=True, verbose_name='Tag')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('position', models.CharField(choices=[('prefix', 'Prefix'), ('suffix', 'Suffix')], default='suffix', help_text='Prefix tags sort users together in the Mumble channel list.', max_length=6, verbose_name='Position')),
                ('order', models.SmallIntegerField(default=0, help_text='Lower values appear first when a user has several tags.', verbose_name='Order')),
                ('groups', models.ManyToManyField(blank=True, help_text='Members of any of these groups receive this tag.', related_name='mumble_tags', to='auth.group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Tag association',
                'verbose_name_plural': 'Tag associations',
                'ordering': ['order', 'tag'],
            },
        ),
    ]
